'use strict';

/**
 * Position and P&L accounting.
 *
 * Tracks a net position per symbol using average-cost, accrues taker fees, and
 * reports realized and unrealized P&L plus account equity. Kept intentionally
 * explicit so the numbers on the dashboard are auditable — a real dashboard
 * that hides fees/funding is the first thing a trader stops trusting.
 */

const TAKER_FEE_RATE = 0.0004; // 4 bps, roughly a retail spot taker fee

class Portfolio {
  constructor({ startingCash = 100000 } = {}) {
    this.startingCash = startingCash;
    this.realizedPnl = 0;
    this.feesPaid = 0;
    /** @type {Map<string, {qty:number, avgPrice:number}>} qty>0 long, qty<0 short */
    this.positions = new Map();
  }

  _pos(symbol) {
    if (!this.positions.has(symbol)) {
      this.positions.set(symbol, { qty: 0, avgPrice: 0 });
    }
    return this.positions.get(symbol);
  }

  /**
   * Apply a fill. `side` is 'BUY' | 'SELL'; `qty` is always positive.
   * Returns the realized P&L generated by this fill.
   */
  applyFill(symbol, side, qty, price) {
    const pos = this._pos(symbol);
    const fee = qty * price * TAKER_FEE_RATE;
    this.feesPaid += fee;

    const signed = side === 'BUY' ? qty : -qty;
    let realized = 0;

    if (pos.qty === 0 || Math.sign(pos.qty) === Math.sign(signed)) {
      // Opening or adding in the same direction -> blend average price.
      const newQty = pos.qty + signed;
      pos.avgPrice =
        (Math.abs(pos.qty) * pos.avgPrice + Math.abs(signed) * price) /
        Math.abs(newQty);
      pos.qty = newQty;
    } else {
      // Reducing or flipping -> realize P&L on the closed portion.
      const closingQty = Math.min(Math.abs(signed), Math.abs(pos.qty));
      const direction = Math.sign(pos.qty); // +1 long being closed, -1 short
      realized += direction * (price - pos.avgPrice) * closingQty;
      const remaining = pos.qty + signed;
      if (Math.sign(remaining) === Math.sign(pos.qty) || remaining === 0) {
        pos.qty = remaining;
        if (remaining === 0) pos.avgPrice = 0;
      } else {
        // Position flipped through zero; the excess opens a new position.
        pos.qty = remaining;
        pos.avgPrice = price;
      }
    }

    this.realizedPnl += realized;
    return realized;
  }

  unrealized(symbol, markPrice) {
    const pos = this.positions.get(symbol);
    if (!pos || pos.qty === 0 || markPrice == null) return 0;
    return (markPrice - pos.avgPrice) * pos.qty;
  }

  /** Snapshot enriched with live marks for every held symbol. */
  snapshot(priceLookup) {
    const positions = [];
    let totalUnrealized = 0;
    for (const [symbol, pos] of this.positions) {
      if (pos.qty === 0) continue;
      const mark = priceLookup(symbol);
      const uPnl = this.unrealized(symbol, mark);
      totalUnrealized += uPnl;
      positions.push({
        symbol,
        qty: +pos.qty.toFixed(6),
        avgPrice: +pos.avgPrice.toFixed(4),
        markPrice: mark != null ? +mark.toFixed(4) : null,
        unrealizedPnl: +uPnl.toFixed(2),
      });
    }
    const equity =
      this.startingCash + this.realizedPnl + totalUnrealized - this.feesPaid;
    return {
      startingCash: this.startingCash,
      realizedPnl: +this.realizedPnl.toFixed(2),
      unrealizedPnl: +totalUnrealized.toFixed(2),
      feesPaid: +this.feesPaid.toFixed(2),
      equity: +equity.toFixed(2),
      positions,
    };
  }
}

module.exports = { Portfolio, TAKER_FEE_RATE };
